"""rename address

Revision ID: 34a3235862d3
Revises: 542fc31c2fb9
Create Date: 2024-06-26 13:53:27.432856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34a3235862d3'
down_revision = '542fc31c2fb9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'adress', new_column_name='location')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'adress', new_column_name='location')

    # ### end Alembic commands ###
