"""rename department

Revision ID: 542fc31c2fb9
Revises: f156462671a0
Create Date: 2024-06-26 13:42:37.683856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '542fc31c2fb9'
down_revision = 'f156462671a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department', 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('departments', 'department')
    # ### end Alembic commands ###
